# -*- coding: utf-8 -*-
"""assignment day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hGxLT_oDW0-qtduMkSmqX38BIYQCH_zW
"""

#Take input for a list and sort it in descending order.


li = [int(i) for i in input("Enter the values").split()]    # taken input from user to enter values  
li.sort()      # sorted list Ascending order
li.reverse()    # reverse the list that give descending order
print(li)   # print the list